### ISSUE TITLE
Fairseq voice cloning

### ISSUE THREAD

**Issue by Poccapx** [coqui-ai/TTS#3142] opened 2023-11-05 17:02 UTC
### Describe the bug

There seems to be an issue of activating voice conversion in Coqui when using _Fairseq_ models. Argument `--speaker_wav` works fine on identical text with the XTTS model, but with Fairseq it seems to be ignored. Have tried both .wav and .mp3, different lengths, file locations/names, with and without CUDA, several languages. There are no errors, just always the same generic male voice. Is this a known issue with voice cloning and Fairseq on Windows’ command line or is something wrong with my setup?

### Environment

```shell
Windows, tts.exe
```

**Comment by erogol** [comment] 2023-11-08 10:18
Can you give us a code for us to reproduce the problem?

**Comment by Poccapx** [comment] 2023-11-08 10:28
Just running with any Fairseq model normally, the same way as with XTTS (which clones just fine, version 2 included): `tts.exe --use_cuda true --model_name tts_models/[lang]/fairseq/vits --text "Testing voice cloning with Fairseq on Windows." --speaker_wav Test.wav --out_path Fairseq.wav`

**Comment by erogol** [comment] 2023-11-08 10:31
Can you try this? https://tts.readthedocs.io/en/latest/inference.html#example-voice-cloning-by-a-single-speaker-tts-model-combining-with-the-voice-conversion-model

TTS with VC is not supported on terminal AFAIR

**Comment by Poccapx** [comment] 2023-11-08 10:36
The thing is that running `tts.exe --use_cuda true --model_name tts_models/multilingual/multi-dataset/xtts_v2 --language_idx [lang] --text "Testing voice cloning with Fairseq on Windows." speaker_wav Test.wav --out_path XTTS.wav` clones the voice perfectly fine. The problem is with Fairseq models, where the argument `--speaker_wav` seems to be ignored.

**Comment by Sharrnah** [comment] 2023-11-10 19:04
@Poccapx 
for non-voice cloning models, you need to run the resulting TTS audio through a voice conversion model. See
https://github.com/coqui-ai/TTS#voice-conversion-models

XTTS is a voice-cloning model which does this on its own. (And actually can't do without any cloning audio file).

**Comment by Poccapx** [comment] 2023-11-10 19:37
That’s very important, thank you. Is there a list for models regarding `--model_name "<language>/<dataset>/<model_name>"`?

**Comment by Sharrnah** [comment] 2023-11-10 19:45
pretty sure there is currently only one official one, and that is `voice_conversion_models/multilingual/vctk/freevc24`

(not sure if you have to keep the first part "voice_conversion_models" out from the --model_name argument, as i am not using the CLI)

you can find a list of all models here: https://github.com/coqui-ai/TTS/blob/dev/TTS/.models.json#L924

**Comment by Poccapx** [comment] 2023-11-10 19:55
Right! In the string `tts --out_path output/path/speech.wav --model_name "<language>/<dataset>/<model_name>" --source_wav <path/to/speaker/wav> --target_wav <path/to/reference/wav>` what is the difference between arguments _--out_path_ and _--target_wav_?

**Comment by Sharrnah** [comment] 2023-11-10 20:04
--source_wav is the speech audio you want to convert.
--target_wav is the speech you want the source_wav to be converted into
--out_path is the finished converted audio.

**Comment by Poccapx** [comment] 2023-11-12 00:55
Using `voice_conversion_models/multilingual/vctk/freevc24` on top of a Fairseq output has worked. The voice cloning quality is nowhere near that of XTTS, but at least that way it’s possible to switch from the default male voice to a female one. For Fairseq as a non-voice cloning model, is the `--speaker_wav` argument always pointless or are there instances where it is used? Asking this since it’s present in [these](github.com/coqui-ai/TTS#example-text-to-speech-using-fairseq-models-in-1100-languages-) [two](github.com/coqui-ai/TTS/pull/3058) examples, and that got me thinking that something was wrong with my initial setup.

**Comment by Sharrnah** [comment] 2023-11-14 12:22
sorry for the late reply.

for the first example link, its because the `tts_with_vc_to_file()` function does the voice conversion internally already. (thats the "with_vc" part in the function name means)

About your second example, i have actually no idea. I would guess it has to do with the encoder model and not with the TTS model. But thats just a guess. So maybe i was wrong and you can somehow convert speakers using some vocoder models. Haven't found anything in the documentation about it, so maybe ask in the discussions https://github.com/coqui-ai/TTS/discussions about it.

I hate to make advertising, but in case you want, you can give my Application [Whispering Tiger](https://github.com/Sharrnah/whispering-ui) a try. It has multiple TTS plugins (including coqui TTS) and together with the RVC Plugin and a RVCv2 model, you can have probably the currently best voice conversion available. (its currently windows only though)

**Comment by erogol** [comment] 2023-11-28 11:05
should be fixed by now.

**Closed by erogol** 2023-11-28 11:05 UTC
Labels: bug

**Comment by Nanshanelectrician** [comment] 2023-12-15 10:22
> 你能试试这个吗？ [https://tts.readthedocs.io/en/latest/inference.html#example-voice-cloning-by-a-single-speaker-tts-model-combining-with-the -语音转换模型](https://tts.readthedocs.io/en/latest/inference.html#example-voice-cloning-by-a-single-speaker-tts-model-combining-with-the-voice-conversion-model)
> 
> AFAIR 终端不支持带有 VC 的 TTS

UnboundLocalError: cannot access local variable 'dataset' where it is not associated with a value

**Comment by ROBERT-MCDOWELL** [comment] 2024-11-28 15:12
> should be fixed by now.

apparently not, speaker_wav has no effect at all. thankst to provide an example of how to use our own voice with fairseq through coqui-tts if you can.

**Comment by eginhard** [comment] 2024-11-28 15:45
@ROBERT-MCDOWELL This repo is abandoned, it's only fixed in our fork: https://github.com/idiap/coqui-ai-TTS
Per the documentation:
```python
api = TTS("tts_models/deu/fairseq/vits")
api.tts_with_vc_to_file(
    "Wie sage ich auf Italienisch, dass ich dich liebe?",
    file_path="output.wav",
    speaker_wav="reference.wav",
)
```

**Comment by ROBERT-MCDOWELL** [comment] 2024-11-28 16:16
sorry I thought I was at https://github.com/idiap/coqui-ai-TTS/
anyhow it's the same. this speaker_wav is a mystery. no effect at all...
Or does it need a voice conversion? how to integrate my own voice into the fairesq model....

**Comment by ROBERT-MCDOWELL** [comment] 2024-11-28 16:19
ok my bad, it's working but it's mixed with the default cloned voice of fairseq.... but the tone is more near the default than the custom voice.

**Comment by eginhard** [comment] 2024-11-28 18:52
Yes, Fairseq models don't have integrated voice cloning. FreeVC is used then for voice conversion, which is not very good.

**Comment by ROBERT-MCDOWELL** [comment] 2024-11-28 19:29
is it possible to convert fairesq model to XTTS-v2 or is the structure is completely different?
ok I can see in the cache when it download the fairseq model it download also the FreeVC folder as I usee tts_to_vc_file.
that's comprehensible now. but this TTS world should really have a squeleton standard very soon. it recalls me the javascript at its start.... a mess.

**Comment by eginhard** [comment] 2024-11-28 20:13
@ROBERT-MCDOWELL It's open source, you're welcome to help improving it

**Comment by ROBERT-MCDOWELL** [comment] 2024-11-28 20:16
it's always a question of time.....
