### ISSUE TITLE
tts_models/en/ljspeech/tacotron2-DDC model does not stop decoding if there is no punctuation at the end of the sentence. 

### ISSUE THREAD

**Issue by davidak** [coqui-ai/TTS#484] opened 2021-05-13 20:03 UTC
**Describe the bug**
In some cases the spoken text is messed up.

**To Reproduce**
1. Run the following command `tts-server --model_name tts_models/en/ljspeech/tacotron2-DDC --vocoder_name vocoder_models/en/ljspeech/hifigan_v2`
2. open webinterface and generate audio http://127.0.0.1:5002/
3. text and audio examples:

>banana

https://soundcloud.com/davidak-de/ai-with-tourette-syndrome-struggles-to-say-banana

popular tourette youtuber tells the banana tic story. it's pretty close :D https://youtu.be/Q5MrVcpq-a8?t=74

>dada

https://soundcloud.com/davidak-de/dada-ai-singing

>what have you done??? i'm literally screaming. ha

https://soundcloud.com/davidak-de/disturbed-ai-is-literally-screaming

>shit, fuck! ha

https://soundcloud.com/davidak-de/ai-with-tourette-syndrome-swearing

>what's going on

https://soundcloud.com/davidak-de/ai-total-breakdown

>cyber space
>mastodon
>coqui tts
>cocktail
>noise
>linus
>G
>H
>A

well, every single letter produces 12 seconds noise

the problem seem to be that it does not know where the end is when there is no `.`, `!` or `?` at the end. it just continues speaking what comes to it's mind...

you can try to generate the audio multiple times to get different results. sometimes it's completely confused, but most times only the last word loops

when this issue occur, you see this in terminal:

```
 > Model input: what's going on
 > Text splitted to sentences.
["what's going on"]
   | > Decoder stopped with 'max_decoder_steps
 > Processing time: 7.120903015136719
 > Real-time factor: 0.584658592060488
[INFO] ::ffff:127.0.0.1 - - [13/May/2021 20:45:27] "GET /api/tts?text=what%27s%20going%20on HTTP/1.1" 200 -
```

Related to:

- https://github.com/coqui-ai/TTS/discussions/278
- https://github.com/coqui-ai/TTS/discussions/325
- https://github.com/coqui-ai/TTS/wiki/FAQ#my-tacotron-model-does-not-stop---i-see-decoder-stopped-with-max_decoder_steps---stopnet-does-not-work

**Expected behavior**
read the text like a human would

**Environment (please complete the following information):**
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: NixOS GNU/Linux 21.05pre288911.65d6153aec8 (Okapi)
- **PyTorch or TensorFlow version (use command below)**: which command???
- **Python version**: 3.8.9
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:
- TTS version: 0.0.12

**Additional context**
I hope it's OK to make this joke that the AI has a mental disorder and it's not too offensive.

**Comment by erogol** [comment] 2021-05-13 22:21
The model is trained that way it sees punctuations at the end for every sentence therefore it needs to see to decide the end. It is not necessarily a bug but a bias with the model which can be fixed by training it again considering this issue.

**Comment by davidak** [comment] 2021-05-13 22:36
for an enduser, it is a bug since the TTS is not able to read words or lists

**Comment by erogol** [comment] 2021-05-13 23:20
so what do you suggest?

**Comment by davidak** [comment] 2021-05-14 03:30
>easy fix to your bug is to add punctuation to the end.

i'm just demonstrating the issue. my goal is to improve this project and the quality of the results. changing the text is not always an option. consider using mycroft to read chat messages or tweets

i created this bug report in the hope it will get fixed at some point. at least the issue is tracked

**Comment by erogol** [comment] 2021-05-14 12:52
Another option is to train the model enabling `bos` and `eos` characters so it adds special characters to the end and the beginning and the model knows where to stop. But essentially it is the same thing as adding punctuation for every input. Without this special sign, be it `eos` or punctuation, the model cannot even learn what is the end of a sentence. 

Thanks for the flag again. I agree it is an issue but not a bug in a general sense. So I keep it here.

**Comment by erogol** [comment] 2021-05-14 12:53
just updated the title to be more informative. Hope it is fine with you.

**Closed** 2021-06-20 13:33 UTC
Labels: wontfix
