### ISSUE TITLE
[Bug] LJSpeech VITS Recipe's EvalAudios/eval/audio is broken

### ISSUE THREAD

**Issue by fijipants** [coqui-ai/TTS#1426] opened 2022-03-19 14:41 UTC
## 🐛 Description

When training the LJSpeech VITS recipe, and looking at tensorboard, the `EvalAudios/eval/audio` is always some extremely short clip. Here's an example:

[BAD] `EvalAudios/eval/audio` at step 61k:

https://user-images.githubusercontent.com/88913682/159125459-65c48042-f860-4462-a503-21c64e9b3451.mp4

[GOOD] `TestAudios/0-audio` at step 61k:

https://user-images.githubusercontent.com/88913682/159125480-881b8ed5-7894-4dd1-a79e-c605b60ebfa3.mp4

### To Reproduce

1. Run the recipe
2. Look at Tensorboard

### Expected behavior

Since `EvalAudios/eval/audio` exists, I expect that it has some intelligible audio

### Environment

```json
{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 3090",
            "NVIDIA GeForce RTX 3090"
        ],
        "available": true,
        "version": "11.3"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "1.10.2",
        "TTS": "0.6.1",
        "numpy": "1.19.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.7.11",
        "version": "#202202230823 SMP PREEMPT Wed Feb 23 14:53:24 UTC 2022"
    }
}
```

**Comment by WeberJulian** [comment] 2022-03-24 15:48
Hey, I think this is normal behavior. This is the short sample that is passed to the discriminator. Maybe there should be a full sample from the eval set as well .

**Comment by erogol** [comment] 2022-04-01 08:25
Producing full clips for eval would make the training time a lot longer. We already have the test samples. I don't see how longer eval samples would be useful. 

I close this as it is not a Bug but feel free to continue the discussion.

**Closed by erogol** 2022-04-01 08:25 UTC
Labels: bug
