### ISSUE TITLE
hifigan_generator has Memory Leak

### ISSUE THREAD

**Issue by MultiTrickFox** [coqui-ai/TTS#1297] opened 2022-02-26 15:09 UTC
My code is simple: (nothing out of the ordinary)

wav, alignment, _, _ = synthesis(
model,
sentence,
voice_config,
use_gpu, # -> false.
voice_processor,
speaker_id = None,
d_vector = my_dvector,
style_wav = None,
language_id = 0,
enable_eos_bos_chars = voice_config.enable_eos_bos_chars,
use_griffin_lim = True,
do_trim_silence = False,
).values()

I notice that after running this code multiple times (in a loop), the next runs always add on to the memory - bloating (tested on ubuntu latest and osx). I could post the memory screenshots here but it is trivial to observe. How could I overcome this? Any help would be appreciated, thank you..

**Comment by MultiTrickFox** [comment] 2022-02-27 11:10
Update: I did a deep dive into your code base; inside vits.py the memory leak is caused by:

o = self.waveform_decoder((z * y_mask[:,:,:self.max_inference_len], g=g)

in my case the self.waveform_decoder is a HifiGan ; when this step is bypassed there is no more memory leak (run over 100 iterations with no visible leak compared to non-bypassed original version.)

---

In the past I used various hifigan implementations which all take in a spectrogram argument but your implementation of hifigan seems a bit different to me than others;

right now i'm exploring the hifigan_generator.py for possible causes and/or replacement options which could use the arguments z*y_mask and g.

**Comment by MultiTrickFox** [comment] 2022-02-27 11:37
Update 2: inside hifigan_generator.py here is the exact line that causes the memory leak:
            
for j in range(self.num_kernels):
   if z_sum is None: 
     z_sum = self.resblocks[i * self.num_kernels + j](o)
   else:
     z_sum += self.resblocks[i * self.num_kernels + j](o)

I will take a breakfast break and go deeper into resblocks and hopefully give fix in my next update..

**Comment by MultiTrickFox** [comment] 2022-02-27 14:14
Update 3: I opened an issue about weight_norm memory leakage over at pytorch: 
https://github.com/pytorch/pytorch/issues/73481

**Comment by erogol** [comment] 2022-03-01 10:41
Please use the issue template for us to understand and reproduce the issue. 

We use the model internally and don't observe any OOM issues. 

I close this one but feel free to create a new issue filling the issue template.

**Closed by erogol** 2022-03-01 10:41 UTC
Labels: bug

**Comment by NeonBohdan** [comment] 2022-04-27 07:31
@MultiTrickFox Hi
Me helped two things
___
1)
```
with torch.no_grad():
   synthesis(...)
```
____
2)
```
apt install libjemalloc2
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2 python3 run.py
```

**Comment by MultiTrickFox** [comment] 2022-04-27 22:44
Ah yes, the 2nd method, after countless hours on pytorch forums I saw people mention it. It works for some people but not all, not on my Ubuntu LTS.. But thank you :)

I ended up spawning a new process and kill it right after getting the result.. Might help someone someday.

**Comment by automationist** [comment] 2022-06-14 22:43
@MultiTrickFox, I have the exact same issue coming from the exact location you mentioned above. However, I'm not sure when and where to run `torch.nn.utils.remove_weight_norm`. Would you mind giving me a bit more details or the exact code you used? I've been debugging this for hours today! haha

**Comment by MultiTrickFox** [comment] 2022-06-15 11:46
@automationist I removed that part due to reasons I will explain. but for sake of your question, I re-coded it here;

   here is the regular model loading process:

model = setup_model(voice_config)
model.language_manager.set_language_ids_from_file('TTS/language_ids.json')
weights = load('TTS/best_model_latest.pth.tar', map_location='cpu')['model'].copy()
model.load_state_dict(weights)

   you remove all submodule weightnorms of this model
   to do that;

def get_children(model):
    children = list(model.children())
    flat_children = []
    if children == []: return model
    else:
       for child in children:
            try: flat_children.extend(get_children(child))
            except TypeError: flat_children.append(get_children(child))
    return flat_children

for child in get_children(model): remove_weight_norm(child)


   BUT ;

   after long nights of debug; this only fixes half of the memory leak. Rest is from actually the Conv1d of pytorch. checked on pytorch forums and a lot people confirm this for multiple cases. (and then pytorch sends you to intel's mkldnn library as it's their problem instead, and way down the rabbit hole we go.)

   SO ;

   you can use this method: (as mkldnn soft-fix)
apt install libjemalloc2
LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.2 python3 your-script.py
   Which is reported to work for some and not for others.

   or you can spawn a child-process inside python, use that process to calculate your voice result, then kill it; guaranteed to leave no trace.

**Comment by automationist** [comment] 2022-06-15 15:28
@MultiTrickFox, thank you so much! This saves me so much headache. I’ll try the jemalloc trick. I don’t have any memory issues on macOS. 
When you say a child process, are you using like subprocess to initiate a new Synthesizer and kill the process? Because initiating a new Synthesizer can take a while, so this might beat the purpose.

**Comment by MultiTrickFox** [comment] 2022-06-21 23:21
Subprocess, multiprocess.Process, or I did the fork directly.

In my experiments Synthesizer loading was nowhere comparable to the actual synthesis, examples were each of at least 2 sentences. So I doubt it will be a problem

**Comment by pablodz** [comment] 2024-05-08 23:01
+1
