### ISSUE TITLE
Missing required field "periods_multi_period_discriminator"[Bug] 

### ISSUE THREAD

**Issue by Approximetal** [coqui-ai/TTS#1728] opened 2022-07-13 08:23 UTC
### Describe the bug

    raise ValueError(f' [!] Missing required field "{field.name}"')
ValueError:  [!] Missing required field "periods_multi_period_discriminator"

when using pretrained vits models, such as `tts_models/multilingual/multi-dataset/your_tts` and `tts_models/en/ljspeech/vits`
that I found the config,json file does not have parameter named "periods_multi_period_discriminator" 

### To Reproduce

tts --text 'Hello' --model_name 'tts_models/multilingual/multi-dataset/your_tts' --vocoder_name 'vocoder_models/en/ljspeech/hifigan_v2' --out_path en_vits_hifigan.wav

### Environment

```shell
error occours in:
git log : commit 8b75e8be9c269d4aa0d984b4a80fb0b2427f8a09 (HEAD)
HEAD is now at 8b75e8be Bump up to v0.7.0
HEAD detached at bc1f93c2
```

**Comment by Approximetal** [comment] 2022-07-14 03:03
> you don't need to (can't) use a vocoder with yourTTS. But I'll check the field issue.
It still has such issue without vocoder options

**Comment by p0p4k** [comment] 2022-07-15 19:18
I cannot reproduce the bug. 
`tts --text "hello." --model_name tts_models/multilingual/multi-dataset/your_tts --speaker_idx male-en-2 --language_idx en`
The command worked fine for me.

**Comment by erogol** [comment] 2022-07-19 21:52
then I close this

**Closed by erogol** 2022-07-19 21:52 UTC
Labels: bug
