### ISSUE TITLE
RuntimeError when fine-tuning VITS on it's pretrained dataset, with pretrained config.

### ISSUE THREAD

**Issue by BillyBobQuebec** [coqui-ai/TTS#818] opened 2021-09-18 19:19 UTC
When I attempt to fine-tune VITS using the pretrained config, I get this RuntimeError:
```
  File "/home/BillyBobQ/repo/coqui-0.3.1/TTS/utils/audio.py", line 352, in normalize
    raise RuntimeError(" [!] Mean-Var stats does not match the given feature dimensions.")
RuntimeError:  [!] Mean-Var stats does not match the given feature dimensions.
```
Here are the full logs for what happened:
[logs.txt](https://github.com/coqui-ai/TTS/files/7190469/logs.txt)

**To Reproduce**
I attempted to fine-tune the VITS LJ checkpoint on the LJ dataset using the intended pretrained config, (just to see if fine-tuning is working) here are the files I used to do so(it has some slight changes in the config compared to the original json, to work properly with V0.3.1):

[run-lj-small.txt](https://github.com/coqui-ai/TTS/files/7190470/run-lj-small.txt) (sh file changed to txt extension for github upload)

[config.txt](https://github.com/coqui-ai/TTS/files/7190471/config.txt) (json file changed to txt extension for github upload)

[scale_stats.txt](https://github.com/coqui-ai/TTS/files/7190488/scale_stats.txt) (npy file changed to txt extension for github upload)

**Expected behavior**
I expected training to begin, and training data to begin uploading to the tensorboard.

**Environment:**
- **OS Platform and Distribution**: Ubuntu 18.04
- **PyTorch or TensorFlow version**: PyTorch 1.9.0 w/ CUDA 11.1
- **Python version**: 3.7.11
- **CUDA/cuDNN version**: 11.1
- **GPU model and memory**: RTX 3090, 24GB of VRAM, 64GB of RAM.
- **Exact command to reproduce**:  already shown in the sh file I reference under **To Reproduce** section above.

**Additional context**
I'm curious if anyone has had any luck fine-tuning the VITS LJ checkpoint with Coqui, or even training at all with Coqui VITS.

**Comment by erogol** [comment] 2021-09-20 08:21
VITS uses 512 dim spectrograms and the scale_stats you use is probably 80 dim specs. Our pre-trained VITS do not use scale stats originally. I assume you added that. 

If you need, you need to re-compute the stats with VITS audio parameters.

**Comment by BillyBobQuebec** [comment] 2021-09-20 20:28
@erogol  yes you are right I used scale_stats that time, but now when I try without scale_stats I get this:
[logs.txt](https://github.com/coqui-ai/TTS/files/7198439/logs.txt)

I tried both with and without restore path and the same issue happened.

**Comment by BillyBobQuebec** [comment] 2021-09-27 21:44
@erogol bumping this as I'm still having this issue.

**Comment by skol101** [comment] 2021-10-06 20:26
@BillyBobQuebec , why do you need scale_stats to fine tune VITS?

**Comment by BillyBobQuebec** [comment] 2021-10-06 22:54
> @erogol yes you are right I used scale_stats that time, but now when I try without scale_stats I get this: [logs.txt](https://github.com/coqui-ai/TTS/files/7198439/logs.txt)
> 
> I tried both with and without restore path and the same issue happened.
> 
> I also tried switching "num_mels" value from 80 to 512(since that is the only value in the config set to 80) and the same thing happens

@skol101 ^

**Comment by BillyBobQuebec** [comment] 2021-11-07 18:48
Still have not solved this problem!

**Comment by erogol** [comment] 2021-11-08 07:33
In the last logs you shared the problem is that the number of chars you used for training is different than the size of the embedding layer. So you need to reinitialise the embedding layer. 

If you can create a colab notebook I can take a look at it when I have some time. Until then I close this one as it is not being related to the original issue.

**Closed by erogol** 2021-11-08 07:33 UTC
