### ISSUE TITLE
Weird voice when telling the time

### ISSUE THREAD

**Issue by MohamedAliRashad** [coqui-ai/TTS#489] opened 2021-05-19 08:05 UTC
The output of `tts --text "2:30 pm"` is weird.

**Note:** I noticed the same problem with small words like `pm` and `am`

**Comment by erogol** [comment] 2021-05-19 09:30
It is not a bug but a limitation with the trained model. So I remove the bug flag. 

I don't know which model you use but considering going forward as we remove the phoneme support, our current models do not normalize numbers and acronyms. So you need to normalize them and convert them to plain text before giving them to TTS.

**Comment by MohamedAliRashad** [comment] 2021-05-19 10:53
@erogol 
The weird part was actually with `pm` not the numbers



https://user-images.githubusercontent.com/26205298/118801306-24b4b480-b8a1-11eb-8c8e-21e2521799eb.mp4

**Comment by MohamedAliRashad** [comment] 2021-05-19 10:53
I was using the default model

**Comment by erogol** [comment] 2021-05-19 11:04
It is still the same issue. For the model to say it right, It needs to be in the dataset since `pm` is not in the dataset, the model does not know how to say it. 

And also since the dataset is all words and sentences, the model does not also know how to spell. 

Basically, my point is that all these limitations are about the model,  the dataset, and the training procedure.

**Comment by MohamedAliRashad** [comment] 2021-05-19 18:25
Can the default model be trained on things like this and be supported in future versions

**Comment by erogol** [comment] 2021-05-20 08:34
unfortunately not. We use public datasets and they are not tuned for these special cases. Or we need text normalization modules that handle these cases and convert text to be read by TTS. It is in an active discussion on how and what to implement currently. So I close this as being an issue but feel free to continue the discussion.

**Closed by erogol** 2021-05-20 08:34 UTC
