### ISSUE TITLE
[Bug] Glow-TTS, Trained in multi GPU get  KeyError: 'avg_loss'

### ISSUE THREAD

**Issue by Lizh-TW** [coqui-ai/TTS#822] opened 2021-09-20 15:40 UTC
Hi! When I follow to recipes train a glow-tts, I get this error
```
 ! Run is kept in /workspace/tts/glow_tts/glow_tts_chinese-September-20-2021_02+44PM-0000000
Traceback (most recent call last):
  File "/workspace/TTS/TTS/trainer.py", line 919, in fit
    self._fit()
  File "/workspace/TTS/TTS/trainer.py", line 904, in _fit
    self.train_epoch()
  File "/workspace/TTS/TTS/trainer.py", line 738, in train_epoch
    _, _ = self.train_step(batch, batch_num_steps, cur_step, loader_start_time)
  File "/workspace/TTS/TTS/trainer.py", line 685, in train_step
    target_avg_loss = self._pick_target_avg_loss(self.keep_avg_train)
  File "/workspace/TTS/TTS/trainer.py", line 957, in _pick_target_avg_loss
    target_avg_loss = keep_avg_target["avg_loss"]
  File "/workspace/TTS/TTS/utils/generic_utils.py", line 155, in __getitem__
    return self.avg_values[key]
KeyError: 'avg_loss'
```

and current_lr always 0.00000
![image](https://user-images.githubusercontent.com/58511222/134414658-d3babb20-5495-4003-aa98-a0b093335bea.png)

My train file : [train.py.txt](https://github.com/coqui-ai/TTS/files/7196833/train.py.txt)

**Comment by Jaehyoun** [comment] 2021-09-24 05:22
I have the same problem.. :(

**Comment by erogol** [comment] 2021-09-26 16:10
What is the version ?

**Comment by Lizh-TW** [comment] 2021-09-27 14:28
@erogol v0.3.1

**Comment by BoneGoat** [comment] 2021-09-30 13:53
Maybe related, I'm also training glow-tts and performance isn't being updated. So checkpoints aren't saved because the model hasn't improved I guess.

This is at epoch 60 and the stats are always the same:
 --> EVAL PERFORMANCE
     | > avg_loader_time: 0.00281 (+0.00060)
     | > avg_loss: 3.35893 (+0.00000)
     | > avg_log_mle: 0.67408 (+0.00000)
     | > avg_loss_dur: 2.68484 (+0.00000)

I'm on the main branch: https://github.com/coqui-ai/TTS/commit/7f388f26e36c4af0606b9d99b2fb8736430fae4f

**Comment by erogol** [comment] 2021-09-30 16:06
I've just trained glow_tts recipe again. It is now around epoch 55. I don't see any errors or problems. The model also learns just fine. 

I can't help unfortunately if I can't reproduce the issue.

**Comment by Lizh-TW** [comment] 2021-10-01 23:29
@erogol I try again, and this bug seems to occur in multi GPU training.
Trained with multi GPU
![image](https://user-images.githubusercontent.com/58511222/135695268-fff79fd5-b29a-4b96-be49-700910721114.png)
Train with single GPU
![image](https://user-images.githubusercontent.com/58511222/135695444-912644b7-d83e-4fc5-8e54-977ab9baa4e1.png)

**Comment by BoneGoat** [comment] 2021-10-02 07:44
Well, I found my problem. Mixed-precision training is not working for me. Setting mixed_precision to false will fix the problem makes the model align. So I guess it's not related to this issue.

**Comment by erogol** [comment] 2021-10-04 13:02
Nope, both in multi-gpu, single-gpu, mixed-precision, non-mixed-precision things just work fine on my end. 

Make sure there is nothing wrong with the config you use for the training. 

@Lizh-TW  what is `data_dep_init_steps` in your config ?

**Comment by Lizh-TW** [comment] 2021-10-05 06:39
@erogol my `data_dep_init_steps` is 10.

**Comment by erogol** [comment] 2021-10-05 13:24
then I don't have a guess about what the problem is, unfortunately.

**Comment by Lizh-TW** [comment] 2021-11-04 13:08
@erogol  I when I train in 1 GPU I get this warning then back to normal, but in multi GPU not get.
![image](https://user-images.githubusercontent.com/58511222/140318470-40ddcfde-b510-4029-8e98-8b931331ddf7.png)

   /workspace/TTS/TTS/trainer.py:636: FutureWarning: Non-finite norm encountered in torch.nn.utils.clip_grad_norm_; continuing anyway. Note that the default behavior will change in a future release to error out if a non-finite total norm is encountered. At that point, setting error_if_nonfinite=false will be required to retain the old behavior.
  grad_norm = torch.nn.utils.clip_grad_norm_(self.master_params(optimizer), grad_clip)

**Comment by Lizh-TW** [comment] 2021-11-06 01:43
**My Environment:**
- **Docker : [pytorch:1.9.0-cuda11.1-cudnn8-runtime](https://hub.docker.com/layers/pytorch/pytorch/1.9.0-cuda11.1-cudnn8-runtime/images/sha256-e04020e1b6cc744659c70f5afdc0ab602486f24d74f9ba44929c14b7442dca31?context=explore)
- **PyTorch and TensorFlow version : 1.9.0 & 2.5.0**:
- **Python version : 3.7.10**:
- **CUDA/cuDNN version 11.1/8**:
- **GPU model and memory : GeForce RTX 3090 x2**:

**Comment by erogol** [comment] 2021-11-08 07:25
It is not an issue but just a warning due to Pytorch. So it is fine. 

I also close this issue. I believe it is not there anymore.

**Closed by erogol** 2021-11-08 07:25 UTC
Labels: bug

**Comment by patdflynn** [comment] 2021-11-28 22:30
We're also having this same issue with RTX 3090s. Training with a single 3090 works fine but distributed yields:
![image](https://user-images.githubusercontent.com/44388720/143788733-bc8a36b4-2644-4910-80e8-78130d6c04d7.png)

**Comment by skol101** [comment] 2021-11-29 14:46
> We're also having this same issue with RTX 3090s. Training with a single 3090 works fine but distributed yields:

Could you connected to https://github.com/coqui-ai/TTS/issues/976#issuecomment-981700285 ?

**Comment by erogol** [comment] 2021-11-30 08:54
@patdflynn  so what is the problem? small learning rate?  
@skol101 how is it the same?
