### ISSUE TITLE
[Bug] Default Docker GPU image giving libcudnn_cnn_infer.so.8. Error: libnvrtc.so on synthesis. 

### ISSUE THREAD

**Issue by davedavis** [coqui-ai/TTS#2613] opened 2023-05-13 22:49 UTC
### Describe the bug

CPU image synthesis working fine. But using the web UI on localhost:5002 (UI loads fine), gives a CUDA error when attempting synthesis. 

Seems the container setup is fine. If it's not something I'm doing wrong, I can take a stab at implementing with NVIDIA container toolkit. 

Some additional debugging below. 

^Croot@338f087aaa28:~# python3 TTS/server/server.py --model_name tts_models/en/vctk/vits --use_cuda true
 > tts_models/en/vctk/vits is already downloaded.
 > Using model: vits
 > Setting up Audio Processor...
 | > sample_rate:22050
 | > resample:False
 | > num_mels:80
 | > log_func:np.log10
 | > min_level_db:0
 | > frame_shift_ms:None
 | > frame_length_ms:None
 | > ref_level_db:None
 | > fft_size:1024
 | > power:None
 | > preemphasis:0.0
 | > griffin_lim_iters:None
 | > signal_norm:None
 | > symmetric_norm:None
 | > mel_fmin:0
 | > mel_fmax:None
 | > pitch_fmin:None
 | > pitch_fmax:None
 | > spec_gain:20.0
 | > stft_pad_mode:reflect
 | > max_norm:1.0
 | > clip_norm:True
 | > do_trim_silence:False
 | > trim_db:60
 | > do_sound_norm:False
 | > do_amp_to_db_linear:True
 | > do_amp_to_db_mel:True
 | > do_rms_norm:False
 | > db_level:None
 | > stats_path:None
 | > base:10
 | > hop_length:256
 | > win_length:1024
 > initialization of speaker-embedding layers.
 * Serving Flask app 'server'
 * Debug mode: off

INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (::)
 * Running on http://[::1]:5002
 * Running on http://[::1]:5002
INFO:werkzeug:Press CTRL+C to quit
INFO:werkzeug:::ffff:172.17.0.1 - - [13/May/2023 22:36:19] "GET / HTTP/1.1" 200 -
INFO:werkzeug:::ffff:172.17.0.1 - - [13/May/2023 22:36:20] "GET /static/coqui-log-green-TTS.png HTTP/1.1" 304 -
 > Model input: Hello there How does this thing work with CUDA toolkit?
 > Speaker Idx: ED

 > Language Idx: 
 > Text splitted to sentences.
['Hello there How does this thing work with CUDA toolkit?']
Could not load library libcudnn_cnn_infer.so.8. Error: libnvrtc.so: cannot open shared object file: No such file or directory

### To Reproduce

Follow the steps here: https://tts.readthedocs.io/en/latest/docker_images.html

docker run --rm -it -p 5002:5002 --gpus all --entrypoint /bin/bash ghcr.io/coqui-ai/tts
python3 TTS/server/server.py --list_models #To get the list of available models
python3 TTS/server/server.py --model_name tts_models/en/vctk/vits --use_cuda true

### Expected behavior

Speech is synthesized using the selected model as with the CPU version, only using the GPU. 

### Environment

```shell
This is from WITHIN the container. Seems it's building what's in the Dockerfile fine.

{
    "CUDA": {
        "GPU": [
            "NVIDIA GeForce RTX 2080 with Max-Q Design"
        ],
        "available": true,
        "version": "11.8"
    },
    "Packages": {
        "PyTorch_debug": false,
        "PyTorch_version": "2.0.0+cu118",
        "TTS": "0.13.3",
        "numpy": "1.23.5"
    },
    "System": {
        "OS": "Linux",
        "architecture": [
            "64bit",
            ""
        ],
        "processor": "x86_64",
        "python": "3.10.6",
        "version": "#7-Ubuntu SMP PREEMPT_DYNAMIC Wed Jan 25 00:08:13 UTC 2023"
    }
}
```

**Comment by ben-z** [comment] 2023-05-16 05:59
Dupe of https://github.com/coqui-ai/TTS/discussions/2440

**Closed** 2023-06-23 17:41 UTC
Labels: bug, wontfix
