### ISSUE TITLE
ARM 64bit - Failed to initialize NumPy: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by fquirin** [coqui-ai/TTS#1059] opened 2022-01-04 18:29 UTC
## 🐛 Description

I wanted to do some testing on Raspberry Pi OS Bullseye 64bit and encountered a dependency problem with Numpy 1.19.5. After successful cloning and building the 0.5.0 version running 'tts' gives the error:
```
UserWarning: Failed to initialize NumPy: module compiled against API version 0xe but this version of numpy is 0xd (Triggered internally at  /root/pytorch/torch/csrc/utils/tensor_numpy.cpp:68.)
```

This seems to be related to an incompatibility between Numpy 1.19.5 and Torch 1.10.1, 1.9.0 and 1.8.1 (all I could try).

I tried upgrading Numpy: `pip install numpy --upgrade` which will install Numpy 1.22.0, but break everything else since the Numpy 1.19.5 dependency seems to be very strict.

### To Reproduce

- Install Raspberry Pi OS Bullseye 64bit
- Install Python and some dependencies. I had to run something like: `sudo apt-get install python3-venv libatlas-base-dev llvm-9 libmecab-dev` and set `sudo ln -s /usr/bin/llvm-config-9 /usr/bin/llvm-config` (not sure if llvm is actually required but I needed it when I played with YourTTS)
- Create virtual env: `python3 -m venv env && source env/bin/activate`
- Clone the repo: `git clone https://github.com/coqui-ai/TTS`
- Build: `cd TTS && pip install -e .`
- Try something simple like: `tts --list_models`

### Expected behavior

All dependencies resolve properly and TTS works.

### Environment

- 🐸TTS Version: 0.5.0
- PyTorch Version: 1.10.1
- Python version: 3.9.2
- OS: Raspberry Pi OS 64bit (Aarch64), Kernel: 5.10.63-v8+
- CUDA/cuDNN version: -
- How you installed PyTorch (`conda`, `pip`, source): pip

**Comment by erogol** [comment] 2022-01-06 10:04
I don't think 🐸TTS is the right place for this. It looks to me more like a Pytorch issue. 

I close this but hope someone with Raspi exp can tag here more info.

**Closed by erogol** 2022-01-06 10:04 UTC
Labels: bug

**Comment by fquirin** [comment] 2022-01-06 10:47
@erogol well I don't think it can be fixed as long as 'tts' has requirement `numpy==1.19.5` :thinking:

**Comment by erogol** [comment] 2022-01-07 15:31
Can you try changing the NumPy version manually and see that works ?

**Comment by fquirin** [comment] 2022-01-07 17:55
I can upgrade Numpy to use it with torch (`pip install numpy --upgrade` see above), but as soon as I have to import TTS it will complain about the wrong Numpy version.
When I played with YourTTS (before it was merged into Coqui) I was able to ignore the TTS error until it crashed eventually (I think it was in speaker manager or something). When I build Coqui from the most recent master it seems to check the Numpy version in advance and refuse to start.

**Comment by erogol** [comment] 2022-01-10 07:40
You can clone and change the requirements.txt to enable relevant versions of numpy to give it a try.

**Comment by fquirin** [comment] 2022-01-12 18:27
My experience says I should rather wait for an official and tested requirements change ;-). I'm pretty sure somebody had a reason to set `numpy==1.19.5` in TTS :sweat_smile: .

**Comment by jbroeckling** [comment] 2022-01-27 12:30
I had the same issue on a Raspberry Pi  4 with Bullseye 64bit and did this:

> You can clone and change the requirements.txt to enable relevant versions of numpy to give it a try.

and installed numpy==1.21.5 and the issue is gone (and till now, nothing else broke down).

[ Btw. I also did  mecab-python3==1.0.4 , instead of 1.0.3 ]
I was using Python 3.7.11

**Comment by fquirin** [comment] 2022-01-27 20:53
> installed numpy==1.21.5 and the issue is gone (and till now, nothing else broke down)

nice.

> I was using Python 3.7.11

Did you downgrade from 3.9? I usually find it pretty troublesome on Pi to use a different version than the default.

**Comment by jbroeckling** [comment] 2022-01-29 14:51
> Did you downgrade from 3.9? I usually find it pretty troublesome on Pi to use a different version than the default.

yea, but for another reason. I just made a Python 3.9 venv and installing TTS with numpy==1.22.1 works and gives me better results. Downgrading Python is not recommended, cause it makes more trouble 😄
