### ISSUE TITLE
Basic use appears to generate unusable output

### ISSUE THREAD

**Issue by danielquinn** [coqui-ai/TTS#979] opened 2021-11-29 21:59 UTC
I wasn't sure how to title this, but following the basic instructions, I did the following:

```
$ pip install tts
$ tts --text hello
$ mpv tts_output.wav
```

The result is attached and... it's pretty bad.  I tried variations using different models:

```
$ tts --text hello --model_name=tts_models/en/ljspeech/tacotron2-DCA
$ tts --text hello --model_name=tts_models/en/ek1/tacotron2
$ tts --text hello --model_name=tts_models/en/ljspeech/glow-tts
```

The results for all of these are unusable.  Have I missed something?  The results seem really all over the place, with `hello` generating some creepy OOoooOOoOoOo noises, but `hello I am a sample text` sounding fabulous.  Unfortunately, my application needs some semblance of predictability, and it's conceivable that I'd want my program to "say hello" so this is causing me some pain :-(

I'm pretty experienced in software development, but have next to no experience with ML so "just train the model to do X" doesn't really mean anything to me.  If I shouldn't consider this library to be off-the-shelf text-to-speech, just let me know and I'll explore other options, but so far it's seemed remarkably user-friendly for an ML project, so I thought I'd give it a go as the voice for my current project.

### Samples

I had to zip these 'cause GitHub doesn't allow .wav files.

* [tts --text "hello"](https://github.com/coqui-ai/TTS/files/7621369/tts_output.zip)  (Bad)
* [tts --text "hello I am a sample text"](https://github.com/coqui-ai/TTS/files/7621379/tts_output.zip) (Great!)

**Comment by DelanoLeslie** [comment] 2021-11-30 02:55
Try giving the input punctuation like "Hello." or "Hello, this is a sample."

I think this should help. A majority of the time the datasets these models are trained use punctuation, so the lack of punctuation may confuse it.

**Comment by erogol** [comment] 2021-11-30 08:58
You need to add punctuations since all the models are trained with punctuated sentences. 

I close this as it is not a bug

**Closed by erogol** 2021-11-30 08:58 UTC
