### ISSUE TITLE
[Bug] ValueError: Model is not multi-lingual but `language` is provided.

### ISSUE THREAD

**Issue by lucasjinreal** [coqui-ai/TTS#3188] opened 2023-11-10 06:12 UTC
### Describe the bug

ValueError: Model is not multi-lingual but `language` is provided.

tts = TTS(model_name='xtts-v2', model_path="XTTS-v2/", config_path='XTTS-v2/config.json', gpu=True)

# generate speech by cloning a voice using default settings
tts.tts_to_file(text="It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent.",
                file_path="output.wav",
                speaker_wav="data/沈腾_04.MP3",
                language="en")

### To Reproduce

tts = TTS(model_name='xtts-v2', model_path="XTTS-v2/", config_path='XTTS-v2/config.json', gpu=True)

# generate speech by cloning a voice using default settings
tts.tts_to_file(text="It took me quite a long time to develop a voice, and now that I have it I'm not going to be silent.",
                file_path="output.wav",
                speaker_wav="data/沈腾_04.MP3",
                language="en")

### Environment

```shell
TTS install from git directly newest
```

**Comment by jbang2004** [comment] 2023-11-12 06:40
兄弟，定位到api.py中把if not self.is_multi_lingual and language is not None:这行给注释掉就行了

**Comment by lucasjinreal** [comment] 2023-11-12 07:01
@jbang2004 thanks, I know how to resolve, just report a bug to the team.

**Comment by erogol** [comment] 2023-11-13 14:01
I don't understand what the issue is here. the model name you gave in the sample code is wrong. So I can't really reproduce

**Comment by vitaliy-sharandin** [comment] 2023-11-14 16:25
I have encountered same error when I am trying to use xtts2 multilingual model in loop to generate several audio clips. This happens only for this model, VITS works fine while looping over existing.

**Reproduction code:**
```python
tts = TTS('tts_models/multilingual/multi-dataset/xtts_v2', gpu=True)
for i in range(5):
    tts.tts_with_vc_to_file(text=f"Как оно {i}?", speaker_wav='/content/drive/MyDrive/Data/SPEAKER_00_voice_clips.wav', language='ru', file_path=f'/content/drive/MyDrive/Data/test{i}.wav')
    del tts; import gc; gc.collect(); torch.cuda.empty_cache()
```
**Error:**
```python
/usr/local/lib/python3.10/dist-packages/TTS/api.py in tts_with_vc_to_file(self, text, language, speaker_wav, file_path)
    486                 Output file path. Defaults to "output.wav".
    487         """
--> 488         wav = self.tts_with_vc(text=text, language=language, speaker_wav=speaker_wav)
    489         save_wav(wav=wav, path=file_path, sample_rate=self.voice_converter.vc_config.audio.output_sample_rate)

/usr/local/lib/python3.10/dist-packages/TTS/api.py in tts_with_vc(self, text, language, speaker_wav)
    461         with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as fp:
    462             # Lazy code... save it to a temp file to resample it while reading it for VC
--> 463             self.tts_to_file(text=text, speaker=None, language=language, file_path=fp.name, speaker_wav=speaker_wav)
    464         if self.voice_converter is None:
    465             self.load_vc_model_by_name("voice_conversion_models/multilingual/vctk/freevc24")

/usr/local/lib/python3.10/dist-packages/TTS/api.py in tts_to_file(self, text, speaker, language, speaker_wav, emotion, speed, pipe_out, file_path, **kwargs)
    389                 Additional arguments for the model.
    390         """
--> 391         self._check_arguments(speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
    392 
    393         if self.csapi is not None:

/usr/local/lib/python3.10/dist-packages/TTS/api.py in _check_arguments(self, speaker, language, speaker_wav, emotion, speed, **kwargs)
    240                 raise ValueError("Model is not multi-speaker but `speaker` is provided.")
    241             if not self.is_multi_lingual and language is not None:
--> 242                 raise ValueError("Model is not multi-lingual but `language` is provided.")
    243             if not emotion is None and not speed is None:
    244                 raise ValueError("Emotion and speed can only be used with Coqui Studio models.")

ValueError: Model is not multi-lingual but `language` is provided.
```

Then, if you remove parameter, the launch will trigger exception requiring you to return `language` parameter back.
```python
/usr/local/lib/python3.10/dist-packages/TTS/api.py in tts_with_vc_to_file(self, text, language, speaker_wav, file_path)
    486                 Output file path. Defaults to "output.wav".
    487         """
--> 488         wav = self.tts_with_vc(text=text, language=language, speaker_wav=speaker_wav)
    489         save_wav(wav=wav, path=file_path, sample_rate=self.voice_converter.vc_config.audio.output_sample_rate)

/usr/local/lib/python3.10/dist-packages/TTS/api.py in tts_with_vc(self, text, language, speaker_wav)
    461         with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as fp:
    462             # Lazy code... save it to a temp file to resample it while reading it for VC
--> 463             self.tts_to_file(text=text, speaker=None, language=language, file_path=fp.name, speaker_wav=speaker_wav)
    464         if self.voice_converter is None:
    465             self.load_vc_model_by_name("voice_conversion_models/multilingual/vctk/freevc24")

/usr/local/lib/python3.10/dist-packages/TTS/api.py in tts_to_file(self, text, speaker, language, speaker_wav, emotion, speed, pipe_out, file_path, **kwargs)
    389                 Additional arguments for the model.
    390         """
--> 391         self._check_arguments(speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
    392 
    393         if self.csapi is not None:

/usr/local/lib/python3.10/dist-packages/TTS/api.py in _check_arguments(self, speaker, language, speaker_wav, emotion, speed, **kwargs)
    236                 raise ValueError("Model is multi-speaker but no `speaker` is provided.")
    237             if self.is_multi_lingual and language is None:
--> 238                 raise ValueError("Model is multi-lingual but no `language` is provided.")
    239             if not self.is_multi_speaker and speaker is not None and "voice_dir" not in kwargs:
    240                 raise ValueError("Model is not multi-speaker but `speaker` is provided.")

ValueError: Model is multi-lingual but no `language` is provided.
```

**Temporary fix:**
As a workaround I have put `tts` object within loop and for some reason it works with constant reinitialization. Although it's eating away RAM(up to 9gb and then stops), the error disappears and the generation works.
```python
for i in range(5):
    tts = TTS('tts_models/multilingual/multi-dataset/xtts_v2', gpu=True)
    tts.tts_with_vc_to_file(text=f"Как оно {i}?", speaker_wav='/content/drive/MyDrive/Data/SPEAKER_00_voice_clips.wav', language='ru', file_path=f'/content/drive/MyDrive/Data/test{i}.wav')
    del tts; import gc; gc.collect(); torch.cuda.empty_cache()
```

**Comment by Kaszanas** [comment] 2023-11-17 23:33
> I have encountered same error when I am trying to use xtts2 multilingual model in loop to generate several audio clips. This happens only for this model, VITS works fine while looping over object initialized once.
> 
> **Reproduction code:**
> 
> ```python
> tts = TTS('tts_models/multilingual/multi-dataset/xtts_v2', gpu=True)
> for i in range(5):
>     tts.tts_with_vc_to_file(text=f"Как оно {i}?", speaker_wav='/content/drive/MyDrive/Data/SPEAKER_00_voice_clips.wav', language='ru', file_path=f'/content/drive/MyDrive/Data/test{i}.wav')
> ```
> 
> **Error:**
> 
> ```python
> /usr/local/lib/python3.10/dist-packages/TTS/api.py in tts_with_vc_to_file(self, text, language, speaker_wav, file_path)
>     486                 Output file path. Defaults to "output.wav".
>     487         """
> --> 488         wav = self.tts_with_vc(text=text, language=language, speaker_wav=speaker_wav)
>     489         save_wav(wav=wav, path=file_path, sample_rate=self.voice_converter.vc_config.audio.output_sample_rate)
> 
> /usr/local/lib/python3.10/dist-packages/TTS/api.py in tts_with_vc(self, text, language, speaker_wav)
>     461         with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as fp:
>     462             # Lazy code... save it to a temp file to resample it while reading it for VC
> --> 463             self.tts_to_file(text=text, speaker=None, language=language, file_path=fp.name, speaker_wav=speaker_wav)
>     464         if self.voice_converter is None:
>     465             self.load_vc_model_by_name("voice_conversion_models/multilingual/vctk/freevc24")
> 
> /usr/local/lib/python3.10/dist-packages/TTS/api.py in tts_to_file(self, text, speaker, language, speaker_wav, emotion, speed, pipe_out, file_path, **kwargs)
>     389                 Additional arguments for the model.
>     390         """
> --> 391         self._check_arguments(speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
>     392 
>     393         if self.csapi is not None:
> 
> /usr/local/lib/python3.10/dist-packages/TTS/api.py in _check_arguments(self, speaker, language, speaker_wav, emotion, speed, **kwargs)
>     240                 raise ValueError("Model is not multi-speaker but `speaker` is provided.")
>     241             if not self.is_multi_lingual and language is not None:
> --> 242                 raise ValueError("Model is not multi-lingual but `language` is provided.")
>     243             if not emotion is None and not speed is None:
>     244                 raise ValueError("Emotion and speed can only be used with Coqui Studio models.")
> 
> ValueError: Model is not multi-lingual but `language` is provided.
> ```
> 
> Then, if you remove parameter, the launch will trigger exception requiring you to return `language` parameter back.
> 
> ```python
> /usr/local/lib/python3.10/dist-packages/TTS/api.py in tts_with_vc_to_file(self, text, language, speaker_wav, file_path)
>     486                 Output file path. Defaults to "output.wav".
>     487         """
> --> 488         wav = self.tts_with_vc(text=text, language=language, speaker_wav=speaker_wav)
>     489         save_wav(wav=wav, path=file_path, sample_rate=self.voice_converter.vc_config.audio.output_sample_rate)
> 
> /usr/local/lib/python3.10/dist-packages/TTS/api.py in tts_with_vc(self, text, language, speaker_wav)
>     461         with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as fp:
>     462             # Lazy code... save it to a temp file to resample it while reading it for VC
> --> 463             self.tts_to_file(text=text, speaker=None, language=language, file_path=fp.name, speaker_wav=speaker_wav)
>     464         if self.voice_converter is None:
>     465             self.load_vc_model_by_name("voice_conversion_models/multilingual/vctk/freevc24")
> 
> /usr/local/lib/python3.10/dist-packages/TTS/api.py in tts_to_file(self, text, speaker, language, speaker_wav, emotion, speed, pipe_out, file_path, **kwargs)
>     389                 Additional arguments for the model.
>     390         """
> --> 391         self._check_arguments(speaker=speaker, language=language, speaker_wav=speaker_wav, **kwargs)
>     392 
>     393         if self.csapi is not None:
> 
> /usr/local/lib/python3.10/dist-packages/TTS/api.py in _check_arguments(self, speaker, language, speaker_wav, emotion, speed, **kwargs)
>     236                 raise ValueError("Model is multi-speaker but no `speaker` is provided.")
>     237             if self.is_multi_lingual and language is None:
> --> 238                 raise ValueError("Model is multi-lingual but no `language` is provided.")
>     239             if not self.is_multi_speaker and speaker is not None and "voice_dir" not in kwargs:
>     240                 raise ValueError("Model is not multi-speaker but `speaker` is provided.")
> 
> ValueError: Model is multi-lingual but no `language` is provided.
> ```
> 
> **Temporary fix:** As a workaround I have put `tts` object within loop and for some reason it works with constant reinitialization. Although it's eating away RAM(up to 9gb and then stops), the error disappears and the generation works.
> 
> ```python
> for i in range(5):
>     tts = TTS('tts_models/multilingual/multi-dataset/xtts_v2', gpu=True)
>     tts.tts_with_vc_to_file(text=f"Как оно {i}?", speaker_wav='/content/drive/MyDrive/Data/SPEAKER_00_voice_clips.wav', language='ru', file_path=f'/content/drive/MyDrive/Data/test{i}.wav')
>     del tts; import gc; gc.collect(); torch.cuda.empty_cache()
> ```

I have the same issue but the workaround retriggers model download at each iteration.

**Comment by vitaliy-sharandin** [comment] 2023-11-18 16:57
> 
> I have the same issue but the workaround retriggers model download at each iteration.

I have experienced that too for some time, now it's gone, the models for tts and voice cloning are being reused and ~9GB limit still holds if you clean the newly initialized model every time.
![image](https://github.com/coqui-ai/TTS/assets/14151437/ea9c369b-5fee-4d0d-805f-3d3fdb14cd99)
![image](https://github.com/coqui-ai/TTS/assets/14151437/2628b570-c063-496b-89cf-f95287b1bf6c)

**Comment by JJun-Guo** [comment] 2023-11-21 09:16
> 兄弟，定位到api.py中把if not self.is_multi_lingual and language is not None:这行给注释掉就行了
哥们，注释掉又报错。  File "TTS/tts/layers/xtts/tokenizer.py", line 650, in encode
    return self.tokenizer.encode(txt).ids
AttributeError: 'NoneType' object has no attribute 'encode'
这个遇到了吗？

**Comment by erogol** [comment] 2023-11-28 11:03
It should be fixed in the latest release. Reopen if not.

**Closed by erogol** 2023-11-28 11:03 UTC
Labels: bug

**Comment by JJun-Guo** [comment] 2023-12-01 09:35
> It should be fixed in the latest release. Reopen if not.

File "TTS/tts/layers/xtts/tokenizer.py", line 650, in encode
return self.tokenizer.encode(txt).ids
AttributeError: 'NoneType' object has no attribute 'encode'

**Comment by ordigital** [comment] 2024-01-19 20:02
> > It should be fixed in the latest release. Reopen if not.
> 
> File "TTS/tts/layers/xtts/tokenizer.py", line 650, in encode return self.tokenizer.encode(txt).ids AttributeError: 'NoneType' object has no attribute 'encode'

Check if vocab_path to vocab.json is valid.
```tts.load_checkpoint(config, checkpoint_path='/your/path/to/model.pth', vocab_path=/your/path/to/vocab.json', use_deepspeed=False)```

**Comment by feesec** [comment] 2024-02-22 13:08
我也遇到了，错误表示应该有参数`language`没有并正确设置，支持的language有
![image](https://github.com/coqui-ai/TTS/assets/81979996/e9709bee-ab7e-45a7-a99e-9250ad08bb59)
