### ISSUE TITLE
[Bug] Anyway to run this as docker-compose ?

### ISSUE THREAD

**Issue by PeterTucker** [coqui-ai/TTS#3754] opened 2024-05-21 14:01 UTC
### Describe the bug

Anyway to run this as docker-compose ?

### To Reproduce

Anyway to run this as docker-compose ?

### Expected behavior

Anyway to run this as docker-compose ?

### Logs

```shell
Anyway to run this as docker-compose ?
```

### Environment

```shell
Anyway to run this as docker-compose ?
```

### Additional context

Anyway to run this as docker-compose ?

**Comment by eginhard** [comment] 2024-05-21 14:15
Duplicate of https://github.com/coqui-ai/TTS/issues/3745

**Comment by PeterTucker** [comment] 2024-05-21 15:29
@eginhard correct.

**Closed as completed** 2024-07-18 23:47 UTC
Labels: bug, wontfix
